### ISSUE TITLE
Add NGNC To Curated Asset List

### ISSUE THREAD

**Issue by eebuka** [Creit-Tech/stellar-assets#2]
Asset: NGNC
Issuer: GASBV6W7GGED66MXEVC7YZHTWWYMSVYEY35USF2HJZBLABLYIFQGXZY6

Stellar.expert: https://stellar.expert/explorer/public/account/GASBV6W7GGED66MXEVC7YZHTWWYMSVYEY35USF2HJZBLABLYIFQGXZY6?account[]=GASBV6W7GGED66MXEVC7YZHTWWYMSVYEY35USF2HJZBLABLYIFQGXZY6

**Comment by earrietadev** [comment]
Asset added to the curated list because it was easy to find all the details but for future assets please add the requirements listed here https://github.com/Creit-Tech/stellar-assets#curated-list when requesting a new addition
